from backend.workflows.feedback_pipeline import run_feedback_pipeline
from backend.workflows.prd_pipeline import run_prd_pipeline
from backend.workflows.roadmap_pipeline import run_roadmap_pipeline

def run_end_to_end_pipeline(source: str, user_type: str, text: str, category: str, feature_title: str, reach: float, impact: float, conf: float, effort: float):
    fb_res = run_feedback_pipeline(source, user_type, text, category)
    prd_res = run_prd_pipeline(feature_title, user_type, text, "Auto requirements generated by Copilot.", reach, impact, conf, effort)
    roadmap_res = run_roadmap_pipeline()
    return {
        "feedback_stage": fb_res,
        "prd_stage": prd_res,
        "roadmap_stage": roadmap_res
    }